name: podcast_translator
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - ffmpeg
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - numpy>=1.21.0,<1.25.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - pyyaml>=6.0
  - requests>=2.25.0
  - tqdm>=4.64.1
  - pip:
    - openai-whisper>=20231117
    - gtts>=2.3.0
    - pydub>=0.25.1
    - soundfile>=0.12.0
    - librosa>=0.10.0
    - scikit-learn>=1.0.0
    - fsspec>=2023.6.0
    - packaging>=23.1
    - unidecode>=1.3.2
    - inflect>=5.6.0
    - anyascii>=0.3.0
    - flask>=2.0.1
    - aiohttp>=3.8.1
    - backports.tarfile>=1.0.0
    - numba>=0.57.0
    - llvmlite>=0.40.0
    # Uncomment for voice cloning support (requires additional setup)
    # - TTS>=0.20.0 